[package]
name = "smart_contract_event_listener"
version = "0.1.0"
edition = "2021"

[dependencies]
web3 = { version = "0.19"}
tokio = { version = "1", features = ["full"] }
dotenv = "0.15"
serde = "1.0"
serde_json = "1.0"
futures = "0.3"